services:
  mysql:
    image: 
       mysql:9.7.1
    environment:
       MYSQL_DATABASE: bdd_camagru
       MYSQL_USER: yantoine
       MYSQL_PASSWORD: yantoine_password
       MYSQL_ALLOW_EMPTY_PASSWORD: no
       MYSQL_RANDOM_ROOT_PASSWORD: yes
       network_mode: bridge
    volumes:
       - db-data:/var/lib/mysql
    ports:
       - "3306:3306"

volumes:
  db-data:
    name: "db-data"
    driver: local
