services:
  mysql:
    image: 
       mysql:9.7.1
    container_name:
       camagru_mysql
    environment:
       MYSQL_DATABASE: bdd_camagru
       MYSQL_USER: yantoine
       MYSQL_PASSWORD: yantoine_password
       MYSQL_ALLOW_EMPTY_PASSWORD: no
       MYSQL_RANDOM_ROOT_PASSWORD: yes
       network_mode: bridge
    volumes:
       - db-data:/var/lib/mysql
    ports:
       - "3306:3306"

  nginx:
    build:
      context: ./containers/nginx/.
      dockerfile: Dockerfile
    container_name:
      camagru_nginx
    ports:
      - "8080:80"

  php_fpm:
    build:
      context: ./containers/php/.
      dockerfile: Dockerfile
    container_name:
      camagru_php_fpm
    ports:
      - "9000:9000"


volumes:
  db-data:
    name: "db-data"
    driver: local
